# Generated by Django 3.2.25 on 2025-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundPack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/images/')),
                ('sound_1', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_1_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_2', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_2_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_3', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_3_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_4', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_4_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_5', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_5_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_6', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_6_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_7', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_7_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_8', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_8_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_9', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_9_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
                ('sound_10', models.FileField(upload_to='sound_packs/sounds/')),
                ('sound_10_image', models.ImageField(blank=True, null=True, upload_to='sound_packs/sounds_thumbnails/')),
            ],
        ),
    ]
