name: Checks

on:
  push:

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test
        # run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py collectstatic --noinput && python manage.py test"
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
